apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-iclhkfii
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-iclhkfii:9ec1baf657c76f959af05db8310861302eeab196@sha256:0c1c9ef8a7219c30fee986dec23628be8c5cade5fed92dbe94d9afe7be873f78
          name: container-image
